"""
routes/dev.py
-------------
Developer utilities and testing endpoints. 
⚠️ FOR DEVELOPMENT AND DEMO PURPOSES ONLY ⚠️
"""

import uuid
from datetime import date, timedelta
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.database import get_db
from app.models.crop_models import CropSeason, FarmingAction
from app.engine import run_engine
from app.timeline import build_timeline
from app.routes.seasons import estimate_harvest_date

router = APIRouter(prefix="/dev", tags=["Developer Tools"])

class TestSeasonRequest(BaseModel):
    crop_name: str
    days_since_sowing: int
    simulate_irrigation: bool = False
    simulate_fertilizer: bool = False
    simulate_weeding: bool = False
    simulate_pesticide: bool = False
    simulate_fungicide: bool = False

@router.post("/generate-test-season", summary="[DEV] Generate a test season with simulated actions")
def generate_test_season(data: TestSeasonRequest, db: Session = Depends(get_db)):
    """
    ⚠️ FOR DEVELOPMENT AND DEMO PURPOSES ONLY ⚠️
    
    Automatically creates a crop season, backdates the sowing date by 'days_since_sowing',
    simulates selected actions (irrigation/fertilizer), runs the recommendation 
    engine, and returns the full timeline and health score in one payload.
    """
    # 1. Calculate correct sowing date
    sowing_date_obj = date.today() - timedelta(days=data.days_since_sowing)
    sowing_date_str = sowing_date_obj.isoformat()
    
    harvest_date = estimate_harvest_date(data.crop_name, sowing_date_str)
    season_id = str(uuid.uuid4())

    # 2. Create the season
    season = CropSeason(
        season_id=season_id,
        field_id="dev-test-field",
        farmer_id="dev-test-farmer",
        crop_name=data.crop_name.strip().title(),
        crop_variety="Test Variety",
        sowing_date=sowing_date_str,
        expected_harvest_date=harvest_date,
        current_stage="SOWING", # Will be auto-updated by the engine
        status="ACTIVE",
        notes="Generated by test endpoint",
    )
    db.add(season)
    
    simulated_actions = []

    # 3. Simulate actions — dates anchored to sowing_date so they land
    #    inside the milestone windows defined in CROP_MILESTONES.
    crop_key = data.crop_name.strip().lower()

    # Per-crop irrigation intervals (must match CROP_IRRIGATION_INTERVALS in timeline.py)
    IRRIGATION_INTERVAL = {"wheat": 10, "rice": 3, "maize": 7, "tomato": 4}.get(crop_key, 10)
    FERTILIZER_DAY  = {"wheat": 21, "rice": 20, "maize": 21, "tomato": 25}.get(crop_key, 21)
    WEEDING_DAY     = {"wheat": 21, "rice": 25, "maize": 21, "tomato": 25}.get(crop_key, 21)
    PESTICIDE_DAY   = {"wheat": 45, "rice": 35, "maize": 30, "tomato": 35}.get(crop_key, 45)
    FUNGICIDE_DAY   = {"wheat": 60, "rice": 60, "maize": 50, "tomato": 45}.get(crop_key, 60)

    if data.simulate_irrigation:
        # Log one irrigation action per interval period that has elapsed since sowing
        # e.g. wheat interval=10: log at day 10, 20, 25 (up to days_since_sowing)
        irr_day = IRRIGATION_INTERVAL
        while irr_day <= data.days_since_sowing:
            irr_date = (sowing_date_obj + timedelta(days=irr_day)).isoformat()
            db.add(FarmingAction(
                action_id=str(uuid.uuid4()),
                season_id=season_id,
                farmer_id="dev-test-farmer",
                action_type="IRRIGATION",
                action_date=irr_date,
                notes=f"Simulated irrigation at day {irr_day}",
                is_synced=True
            ))
            irr_day += IRRIGATION_INTERVAL
        simulated_actions.append("IRRIGATION")

    if data.simulate_fertilizer:
        fert_date = (sowing_date_obj + timedelta(days=FERTILIZER_DAY)).isoformat()
        db.add(FarmingAction(
            action_id=str(uuid.uuid4()),
            season_id=season_id,
            farmer_id="dev-test-farmer",
            action_type="FERTILIZER_APPLICATION",
            action_date=fert_date,
            notes="Simulated test fertilizer",
            is_synced=True
        ))
        simulated_actions.append("FERTILIZER_APPLICATION")

    if data.simulate_weeding:
        weed_date = (sowing_date_obj + timedelta(days=WEEDING_DAY)).isoformat()
        db.add(FarmingAction(
            action_id=str(uuid.uuid4()),
            season_id=season_id,
            farmer_id="dev-test-farmer",
            action_type="WEEDING",
            action_date=weed_date,
            notes="Simulated test weeding",
            is_synced=True
        ))
        simulated_actions.append("WEEDING")

    if data.simulate_pesticide:
        pest_date = (sowing_date_obj + timedelta(days=PESTICIDE_DAY)).isoformat()
        db.add(FarmingAction(
            action_id=str(uuid.uuid4()),
            season_id=season_id,
            farmer_id="dev-test-farmer",
            action_type="PESTICIDE_SPRAY",
            action_date=pest_date,
            notes="Simulated test pesticide",
            is_synced=True
        ))
        simulated_actions.append("PESTICIDE_SPRAY")

    if data.simulate_fungicide:
        fung_date = (sowing_date_obj + timedelta(days=FUNGICIDE_DAY)).isoformat()
        db.add(FarmingAction(
            action_id=str(uuid.uuid4()),
            season_id=season_id,
            farmer_id="dev-test-farmer",
            action_type="FUNGICIDE_SPRAY",
            action_date=fung_date,
            notes="Simulated test fungicide",
            is_synced=True
        ))
        simulated_actions.append("FUNGICIDE_SPRAY")

    db.commit()
    db.refresh(season)

    # 4. Run the recommendation engine (this also updates current_stage)
    engine_result = run_engine(season, db)
    
    # Refresh season again since engine likely updated the current_stage directly to DB
    db.refresh(season)

    # 5. Fetch timeline
    timeline = build_timeline(season, db)

    # 6. Return combined payload
    return {
        "message": "Test season created successfully",
        "crop_name": season.crop_name,
        "season_id": season.season_id,
        "days_since_sowing": engine_result["days_since_sowing"],
        "detected_stage": engine_result["current_stage"],
        "crop_health_score": engine_result["crop_health_score"],
        "health_status": engine_result["health_status"],
        "score_details": engine_result["score_details"],
        "simulated_actions": simulated_actions,
        "recommendations": engine_result["recommendations"],
        "timeline": timeline
    }
